<section id="about-me">
    <div class="container">
        <h1>About Me</h1>
        <p>Lorem Ipsum Dolor Blah blah</p>
    </div>
</section>
<section id="achievements">
    <div class="container">
        <h1>My Achievements</h1>
        <p>Lorem Ipsum Dolor Blah blah</p>
    </div>
</section>
<section id="contact-me">
    <div class="container">
        <h1>Connect with me</h1>    
    </div>
</section>
